#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
chatterbox_dubber.py

Local Russian dubbing pipeline for an SRT produced by the speaker pipeline.

Input:
  - original audio/video
  - translated/compressed SRT with [Speaker N]: text
  - speaker_outputs/Speaker_N.mp3 (generated by speaker_pipeline.py)

Output:
  - a Russian speech-only audio track with the same duration as the source
  - optionally a video with the new track muxed in

The original speaker_pipeline.py is NOT modified by this program.

Important timing behavior:
  * Each subtitle cue defines an allowed speech window.
  * If synthesized speech is shorter than the cue window, it is centered:
        cue_start + (cue_duration - speech_duration) / 2
  * If synthesized speech is longer than the cue window, FFmpeg's atempo is
    used to fit it into the window while preserving pitch as much as possible.
  * Each cue becomes an exact-duration audio segment. Speaker tracks are then
    concatenated onto the global timeline and mixed with one another.
  * For freshly generated WAV files, duration is known directly from the Chatterbox
    waveform tensor, avoiding the ffprobe=N/A failure mode.
  * Failed individual cues are logged and replaced with exact-duration silence so
    a long dubbing job can continue.

Background/dialogue replacement:
  This script intentionally creates a CLEAN Russian speech track. It does not
  claim to remove original dialogue from the source. See the notes printed by
  --help / final output for the limitation and the optional preview mix.
"""

from __future__ import annotations

import argparse
import gc
import hashlib
import inspect
import math
import os
import random
import re
import shutil
import subprocess
import sys
import tempfile
import wave
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import torch
import torchaudio as ta

from chatterbox.mtl_tts import ChatterboxMultilingualTTS


# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------

LANGUAGE_ID = "ru"
DEFAULT_REFERENCE_SECONDS = 12.0
DEFAULT_REFERENCE_MIN_DB = -50.0

# "auto" prefers the newer Multilingual V3 when the installed Chatterbox
# package supports it. Older PyPI 0.1.7 installations transparently fall back
# to V2. V3 removes the problematic alignment analyzer used by V2.
DEFAULT_T3_MODEL = "v3"

DEFAULT_TTS_RETRIES = 3
DEFAULT_MIN_DURATION_RATIO = 0.55
DEFAULT_EXPECTED_CHARS_PER_SECOND = 13.5

DEFAULT_SAMPLE_RATE = 48_000
DEFAULT_CHANNELS = 1

DEFAULT_EXAGGERATION = 0.4
# Chatterbox docs note that cfg_weight=0 helps language transfer when the
# reference clip is in a different language from the output.
DEFAULT_CFG_WEIGHT = 0.0
DEFAULT_TEMPERATURE = 0.75
DEFAULT_MIN_P = 0.02
DEFAULT_TOP_P = 0.95
DEFAULT_REPETITION_PENALTY = 1.1

DEFAULT_MAX_CHARS = 280
DEFAULT_INTERPART_PAUSE = 0.12
DEFAULT_SEED = 0
DEFAULT_FIT_MARGIN_MS = 40
DEFAULT_MAX_SPEEDUP = 1.35


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclass
class Cue:
    index: int
    start: float
    end: float
    speaker: str
    text: str

    @property
    def duration(self) -> float:
        return max(0.0, self.end - self.start)


# ---------------------------------------------------------------------------
# Generic subprocess helpers
# ---------------------------------------------------------------------------

def run_cmd(cmd: list[str], check: bool = True) -> subprocess.CompletedProcess:
    """Run a command and return a completed process with readable errors."""
    try:
        result = subprocess.run(
            cmd,
            check=check,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
    except FileNotFoundError as exc:
        raise RuntimeError(
            f"Executable not found: {cmd[0]!r}. Install FFmpeg and make sure "
            "ffmpeg/ffprobe are available in PATH."
        ) from exc

    if check and result.returncode != 0:
        details = (result.stderr or result.stdout or "").strip()
        raise RuntimeError(
            f"Command failed with exit code {result.returncode}:\n"
            f"{' '.join(map(str, cmd))}\n\n{details}"
        )

    return result


def ensure_ffmpeg() -> None:
    missing = [name for name in ("ffmpeg", "ffprobe") if shutil.which(name) is None]
    if missing:
        raise RuntimeError(
            "Missing required executables: " + ", ".join(missing) + ". "
            "Install FFmpeg and add it to PATH."
        )


def wav_duration(path: Path) -> float | None:
    """Read WAV duration directly from frame count when possible."""
    try:
        with wave.open(str(path), "rb") as wf:
            frames = wf.getnframes()
            rate = wf.getframerate()
            if frames > 0 and rate > 0:
                return frames / float(rate)
    except (wave.Error, EOFError, OSError):
        return None
    return None


def ffprobe_duration(path: Path) -> float:
    """Robust duration reader; WAV uses Python's wave module first."""
    path = Path(path)

    # This completely avoids the ffprobe=N/A failure for valid PCM WAV files.
    if path.suffix.lower() in {".wav", ".wave"}:
        duration = wav_duration(path)
        if duration is not None and duration > 0:
            return duration

    queries = [
        [
            "ffprobe", "-v", "error",
            "-show_entries", "format=duration",
            "-of", "default=noprint_wrappers=1:nokey=1",
            str(path),
        ],
        [
            "ffprobe", "-v", "error",
            "-select_streams", "a:0",
            "-show_entries", "stream=duration",
            "-of", "default=noprint_wrappers=1:nokey=1",
            str(path),
        ],
        [
            "ffprobe", "-v", "error",
            "-select_streams", "a:0",
            "-show_entries", "stream=nb_frames,sample_rate",
            "-of", "default=noprint_wrappers=1:nokey=1",
            str(path),
        ],
    ]

    for cmd in queries:
        result = run_cmd(cmd, check=False)
        values = [line.strip() for line in (result.stdout or "").splitlines() if line.strip()]

        if len(values) == 1 and values[0] != "N/A":
            try:
                duration = float(values[0])
                if math.isfinite(duration) and duration > 0:
                    return duration
            except ValueError:
                pass

        if len(values) >= 2:
            try:
                frames = int(values[0])
                sample_rate = int(values[1])
                if frames > 0 and sample_rate > 0:
                    return frames / float(sample_rate)
            except ValueError:
                pass

    raise RuntimeError(f"Could not determine audio duration of {path}")

def ffprobe_channels(path: Path) -> int:
    result = run_cmd(
        [
            "ffprobe",
            "-v",
            "error",
            "-select_streams",
            "a:0",
            "-show_entries",
            "stream=channels",
            "-of",
            "default=noprint_wrappers=1:nokey=1",
            str(path),
        ]
    )
    try:
        return int(result.stdout.strip())
    except ValueError:
        return 1


def safe_filename(name: str) -> str:
    safe = re.sub(r"[^0-9A-Za-zА-Яа-я._-]+", "_", name)
    return safe.strip("_") or "Speaker"


def set_global_seed(seed: int) -> None:
    if seed == 0:
        return

    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)


# ---------------------------------------------------------------------------
# SRT parsing
# ---------------------------------------------------------------------------

TIME_RE = re.compile(
    r"(?P<start>\d{2}:\d{2}:\d{2},\d{3})\s*-->\s*"
    r"(?P<end>\d{2}:\d{2}:\d{2},\d{3})"
)

SPEAKER_RE = re.compile(
    r"^\s*\[(?P<speaker>[^\]]+)\]\s*:\s*(?P<text>.*)$",
    re.DOTALL,
)


def parse_srt_time(value: str) -> float:
    h, m, sec_ms = value.split(":")
    s, ms = sec_ms.split(",")
    return (
        int(h) * 3600
        + int(m) * 60
        + int(s)
        + int(ms) / 1000.0
    )


def parse_srt(path: Path) -> list[Cue]:
    content = path.read_text(encoding="utf-8-sig")
    blocks = re.split(r"\n\s*\n", content.strip())

    cues: list[Cue] = []

    for block in blocks:
        lines = block.splitlines()
        if len(lines) < 3:
            continue

        try:
            index = int(lines[0].strip())
        except ValueError:
            continue

        time_match = TIME_RE.search(lines[1])
        if not time_match:
            continue

        start = parse_srt_time(time_match.group("start"))
        end = parse_srt_time(time_match.group("end"))
        if end <= start:
            continue

        text = "\n".join(lines[2:]).strip()
        speaker_match = SPEAKER_RE.match(text)
        if not speaker_match:
            # The dubbing pipeline expects speaker labels. Keeping the cue
            # with a visible Unknown Speaker is safer than silently dropping it.
            speaker = "Unknown Speaker"
        else:
            speaker = speaker_match.group("speaker").strip()
            text = speaker_match.group("text").strip()

        text = normalize_text(text)
        if not text:
            continue

        cues.append(
            Cue(
                index=index,
                start=start,
                end=end,
                speaker=speaker,
                text=text,
            )
        )

    cues.sort(key=lambda c: (c.start, c.end, c.index))
    return cues


def normalize_text(text: str) -> str:
    text = text.replace("ё", "е").replace("Ё", "Е")
    
    text = re.sub(r"\s+", " ", text)
    return text.strip()


# ---------------------------------------------------------------------------
# Reference voice preparation
# ---------------------------------------------------------------------------

def find_speaker_reference(
    speaker: str,
    speaker_dir: Path,
    reference_dir: Path,
    reference_seconds: float,
    threshold_db: float,
) -> Path:
    """
    Build a short WAV reference from speaker_pipeline.py's concatenated track.

    Existing manually-created <Speaker>.*.wav in reference_dir wins over the
    automatically-created reference, so the user can override a bad sample.
    """
    reference_dir.mkdir(parents=True, exist_ok=True)

    safe = safe_filename(speaker)
    manual_candidates = [
        reference_dir / f"{safe}.wav",
        reference_dir / f"{safe}_ref.wav",
        reference_dir / f"{speaker}.wav",
    ]
    for candidate in manual_candidates:
        if candidate.exists():
            return candidate

    source_candidates = [
        speaker_dir / f"{safe}.mp3",
        speaker_dir / f"{safe}.wav",
        speaker_dir / f"{speaker}.mp3",
        speaker_dir / f"{speaker}.wav",
    ]

    source = next((p for p in source_candidates if p.exists()), None)
    if source is None:
        raise FileNotFoundError(
            f"No speaker sample found for {speaker!r} in {speaker_dir}"
        )

    output = reference_dir / f"{safe}_ref.wav"

    # Convert to 16 kHz mono, remove leading/trailing silence, then cap length.
    # Chatterbox performs its own conditioning, but a clean short prompt is much
    # more practical than passing the entire concatenated speaker track each time.
    audio_filter = (
        f"atrim=0:{reference_seconds:.3f},"
        f"silenceremove="
        f"start_periods=1:start_duration=0.15:start_threshold={threshold_db}dB:"
        f"stop_periods=-1:stop_duration=0.30:stop_threshold={threshold_db}dB," #was stop_periods = 1
        f"asetpts=N/SR/TB"
    )

    run_cmd(
        [
            "ffmpeg",
            "-y",
            "-i",
            str(source),
            "-vn",
            "-ac",
            "1",
            "-ar",
            "16000",
            "-af",
            audio_filter,
            "-c:a",
            "pcm_s16le",
            "-loglevel",
            "error",
            str(output),
        ]
    )

    if not output.exists() or ffprobe_duration(output) < 2: #was 0.25 instead of 2.0
        print(f"WARNING: Auto-generated reference for {speaker} is too short. "
              f"Using simple cut instead.")
        # Fall back to a simple 12s cut in case a particular FFmpeg build does
        # not remove silence as expected.
        run_cmd(
            [
                "ffmpeg",
                "-y",
                "-i",
                str(source),
                "-vn",
                "-ac",
                "1",
                "-ar",
                "16000",
                "-t",
                f"{reference_seconds:.3f}",
                "-c:a",
                "pcm_s16le",
                "-loglevel",
                "error",
                str(output),
            ]
        )

    return output


# ---------------------------------------------------------------------------
# Text splitting for TTS
# ---------------------------------------------------------------------------

def split_tts_text(text: str, max_chars: int) -> list[str]:
    """
    Keep individual Chatterbox requests reasonably short.

    Split first on sentence punctuation, then on commas/spaces if a sentence
    is still too long. This is only a TTS input split; subtitle timing remains
    one single cue window.
    """
    text = normalize_text(text)
    if len(text) <= max_chars:
        return [text]

    sentence_parts = re.split(r"(?<=[.!?…])\s+", text)
    chunks: list[str] = []
    current = ""

    for part in sentence_parts:
        part = part.strip()
        if not part:
            continue

        if not current:
            current = part
            continue

        candidate = current + " " + part
        if len(candidate) <= max_chars:
            current = candidate
        else:
            chunks.append(current)
            current = part

    if current:
        chunks.append(current)

    # A single sentence can still exceed the limit. Split it by clause/word.
    final_chunks: list[str] = []
    for chunk in chunks:
        if len(chunk) <= max_chars:
            final_chunks.append(chunk)
            continue

        clause_parts = re.split(r"(?<=[,;:—-])\s+", chunk)
        current = ""
        for part in clause_parts:
            part = part.strip()
            if not part:
                continue

            if not current:
                current = part
                continue

            candidate = current + " " + part
            if len(candidate) <= max_chars:
                current = candidate
            else:
                final_chunks.append(current)
                current = part

        if current:
            # Last resort: hard word boundary split.
            if len(current) <= max_chars:
                final_chunks.append(current)
            else:
                words = current.split()
                piece = ""
                for word in words:
                    candidate = word if not piece else piece + " " + word
                    if len(candidate) <= max_chars:
                        piece = candidate
                    else:
                        if piece:
                            final_chunks.append(piece)
                        piece = word
                if piece:
                    final_chunks.append(piece)

    return final_chunks or [text]


# ---------------------------------------------------------------------------
# Chatterbox TTS
# ---------------------------------------------------------------------------

class ChatterboxSpeaker:
    def __init__(
        self,
        device: str,
        exaggeration: float,
        cfg_weight: float,
        temperature: float,
        min_p: float,
        top_p: float,
        repetition_penalty: float,
        seed: int,
        t3_model: str = DEFAULT_T3_MODEL,
        tts_retries: int = DEFAULT_TTS_RETRIES,
        min_duration_ratio: float = DEFAULT_MIN_DURATION_RATIO,
    ):
        self.device = device
        self.exaggeration = exaggeration
        self.cfg_weight = cfg_weight
        self.temperature = temperature
        self.min_p = min_p
        self.top_p = top_p
        self.repetition_penalty = repetition_penalty
        self.seed = seed
        self.requested_t3_model = t3_model
        self.tts_retries = max(1, int(tts_retries))
        self.min_duration_ratio = max(0.1, float(min_duration_ratio))
        self.expected_chars_per_second = DEFAULT_EXPECTED_CHARS_PER_SECOND

        print(f"Loading Chatterbox Multilingual TTS on {device}...")
        self.model, self.t3_model = self._load_model(device, t3_model)
        if hasattr(self.model, "eval"):
            self.model.eval()
        print(f"Using multilingual T3 model: {self.t3_model}")

        self.current_reference: Path | None = None
        self.cache: dict[str, Path] = {}

    def _load_model(self, device: str, requested: str):
        """Load V3 when available, otherwise safely fall back to V2."""
        requested = (requested or DEFAULT_T3_MODEL).lower()

        if requested not in {"auto", "v2", "v3"}:
            raise ValueError("--t3-model must be one of: auto, v2, v3")

        supports_t3_model = "t3_model" in inspect.signature(
            ChatterboxMultilingualTTS.from_pretrained
        ).parameters

        if requested in {"auto", "v3"} and supports_t3_model:
            try:
                model = ChatterboxMultilingualTTS.from_pretrained(
                    device=device,
                    t3_model="v3",
                )
                return model, "v3"
            except Exception as exc:
                if requested == "v3":
                    raise RuntimeError(
                        "Requested Chatterbox Multilingual V3, but it could not "
                        f"be loaded: {type(exc).__name__}: {exc}"
                    ) from exc

                print(
                    "WARNING: Multilingual V3 could not be loaded; "
                    f"falling back to V2. Reason: {type(exc).__name__}: {exc}"
                )

        if requested == "v3" and not supports_t3_model:
            raise RuntimeError(
                "The installed Chatterbox package does not support t3_model='v3'. "
                "Your installation is probably the PyPI 0.1.7 line. "
                "Install the current GitHub version to use V3, or run with "
                "--t3-model v2."
            )

        model = ChatterboxMultilingualTTS.from_pretrained(device=device)
        return model, "v2"

    def prepare_reference(self, reference_path: Path) -> None:
        reference_path = reference_path.resolve()

        if self.current_reference == reference_path:
            return

        print(f"Preparing voice reference: {reference_path}")
        self.model.prepare_conditionals(
            str(reference_path),
            exaggeration=self.exaggeration,
        )
        self.current_reference = reference_path

    def _expected_duration(self, text: str) -> float:
        """Conservative speech-duration estimate used only to reject obvious truncation."""
        compact = re.sub(r"\s+", "", text)
        char_count = max(1, len(compact))
        return max(0.45, char_count / self.expected_chars_per_second)

    def _duration_is_plausible(self, text: str, duration: float) -> bool:
        expected = self._expected_duration(text)
        
        min_duration = max(0.45, expected * self.min_duration_ratio)
    
        # НОВОЕ: проверяем максимальную длительность
        # Если аудио больше 5x от ожидаемого, это артефакт
        max_duration = max(5.0, expected * 5)  # минимум 5 секунд или 5x от ожидаемого
        
        if duration > max_duration:
            print(
                f"      WARNING: Generated duration {duration:.3f}s is too long "
                f"(expected ~{expected:.3f}s, max allowed {max_duration:.3f}s). "
                f"Treating as artifact."
            )
            return False
        
        return duration >= min_duration

    def _generation_attempts(self):
        """Return progressively safer sampler settings for early-EOS recovery."""
        attempts = [
            {
                "temperature": self.temperature,
                "min_p": self.min_p,
                "top_p": self.top_p,
                "repetition_penalty": self.repetition_penalty,
                "exaggeration": self.exaggeration,
            }
        ]

        if self.tts_retries >= 2:
            # Lower temperature/repetition pressure and a slightly lower
            # exaggeration make V2 less eager to fall into repetition/EOS loops.
            attempts.append(
                {
                    "temperature": min(self.temperature, 0.65),
                    "min_p": min(self.min_p, 0.02),
                    "top_p": self.top_p,
                    "repetition_penalty": min(self.repetition_penalty, 1.08),
                    "exaggeration": min(self.exaggeration, 0.40),
                }
            )

        if self.tts_retries >= 3:
            # Very conservative fallback. Keep cfg_weight unchanged because 0
            # is deliberately used for cross-language Russian generation.
            attempts.append(
                {
                    "temperature": 0.60,
                    "min_p": 0.0,
                    "top_p": 1.0,
                    "repetition_penalty": 1.0,
                    "exaggeration": 0.35,
                }
            )

        return attempts[: min(self.tts_retries, len(attempts))]

    def _generate_one_part(
        self,
        part: str,
        part_index: int,
        total_parts: int,
    ):
        """Generate one part, retrying when an obvious early EOS is detected."""
        candidates = []

        for attempt_index, params in enumerate(self._generation_attempts(), start=1):
            if self.seed:
                set_global_seed(self.seed + part_index + (attempt_index - 1) * 1000)

            print(
                f"    TTS {part_index + 1}/{total_parts}, attempt {attempt_index}/"
                f"{min(self.tts_retries, 3)}: {part[:90]!r}"
            )

            try:
                wav = self.model.generate(
                    part,
                    language_id=LANGUAGE_ID,
                    exaggeration=params["exaggeration"],
                    cfg_weight=self.cfg_weight,
                    temperature=params["temperature"],
                    min_p=params["min_p"],
                    top_p=params["top_p"],
                    repetition_penalty=params["repetition_penalty"],
                )
            except Exception as exc:
                error_msg = str(exc)
                # Ловим CUDA-ошибки и out-of-range
                if ("CUDA" in error_msg or 
                    "illegal memory access" in error_msg or 
                    "out-of-range" in error_msg or
                    "srcIndex" in error_msg):
                    print(
                        f"      CRITICAL CUDA/FLOW error on attempt {attempt_index}: {error_msg[:200]}"
                    )
                    print("      Resetting CUDA state and retrying...")
                    # Агрессивная очистка памяти
                    gc.collect()
                    if torch.cuda.is_available():
                        torch.cuda.empty_cache()
                        try:
                            torch.cuda.synchronize()
                        except RuntimeError:
                            print("      CUDA context corrupted, continuing anyway...")
                    continue
                else:
                    print(
                        f"      Generation error on attempt {attempt_index}: "
                        f"{type(exc).__name__}: {exc}"
                    )
                    gc.collect()
                    if torch.cuda.is_available():
                        torch.cuda.empty_cache()
                    continue
            except Exception as exc:
                print(
                    f"      Generation error on attempt {attempt_index}: "
                    f"{type(exc).__name__}: {exc}"
                )
                gc.collect()
                if torch.cuda.is_available():
                    torch.cuda.empty_cache()
                continue

            if isinstance(wav, torch.Tensor):
                wav_tensor = wav.detach().cpu()
            else:
                wav_tensor = torch.as_tensor(wav).cpu()

            if wav_tensor.ndim == 1:
                wav_tensor = wav_tensor.unsqueeze(0)
            elif wav_tensor.ndim > 2:
                wav_tensor = wav_tensor.squeeze()
                if wav_tensor.ndim == 1:
                    wav_tensor = wav_tensor.unsqueeze(0)

            duration = int(wav_tensor.shape[-1]) / float(self.model.sr)
            if duration <= 0.01:
                continue

            plausible = self._duration_is_plausible(part, duration)
            print(
                f"      Generated duration: {duration:.3f}s "
                f"({'plausible' if plausible else 'TOO SHORT/LONG'})"
            )
            candidates.append((wav_tensor, duration, plausible, attempt_index))

            # Once we have a plausible result, do not spend more time generating
            # alternatives. The retries are primarily for the early-EOS failure.
            if plausible:
                break

            # Free the unsuccessful tensor before retrying.
            del wav_tensor
            gc.collect()
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

        if not candidates:
            raise RuntimeError("Chatterbox returned no usable waveform after retries.")

        # Prefer the first plausible result. If all attempts were too short,
        # choose the longest one: it is generally less truncated than the others.
        plausible_candidates = [item for item in candidates if item[2]]
        if plausible_candidates:
            chosen = plausible_candidates[0]
        else:
            # Do not turn an entire subtitle into silence just because the
            # conservative heuristic rejected every attempt. Keep the longest
            # generated candidate and make the problem visible in the log.
            chosen = max(candidates, key=lambda item: item[1])
            expected = self._expected_duration(part)
            print(
                f"      WARNING: all attempts were shorter than the safety "
                f"threshold. Using longest={chosen[1]:.3f}s; estimated="
                f"{expected:.3f}s."
            )

        return chosen[0], chosen[1]

    def generate_to_file(
        self,
        text: str,
        reference_path: Path,
        output_path: Path,
        max_chars: int,
        interpart_pause: float,
    ) -> tuple[Path, float]:
        """Generate a cue into WAV and return (path, duration_seconds)."""
        self.prepare_reference(reference_path)

        cache_key = hashlib.sha256(
            (
                str(reference_path.resolve())
                + "\0"
                + text
                + "\0"
                + str(self.seed)
                + "\0"
                + str(self.exaggeration)
                + "\0"
                + str(self.cfg_weight)
                + "\0"
                + str(self.temperature)
                + "\0"
                + str(self.min_p)
                + "\0"
                + str(self.top_p)
                + "\0"
                + str(self.repetition_penalty)
                + "\0"
                + str(self.t3_model)
                + "\0"
                + str(self.tts_retries)
                + "\0"
                + str(self.min_duration_ratio)
            ).encode("utf-8")
        ).hexdigest()

        if cache_key in self.cache and self.cache[cache_key].exists():
            try:
                duration = ffprobe_duration(self.cache[cache_key])
            except Exception:
                duration = 0.0
            if duration > 0.01:
                shutil.copy2(self.cache[cache_key], output_path)
                return output_path, duration
            self.cache.pop(cache_key, None)

        parts = split_tts_text(text, max_chars=max_chars)
        part_paths: list[Path] = []
        part_durations: list[float] = []

        with tempfile.TemporaryDirectory(prefix="chatterbox_parts_") as temp_dir:
            temp_dir_path = Path(temp_dir)

            for i, part in enumerate(parts):
                wav_tensor, generated_duration = self._generate_one_part(
                    part=part,
                    part_index=i,
                    total_parts=len(parts),
                )

                part_path = temp_dir_path / f"part_{i:03d}.wav"
                ta.save(
                    str(part_path),
                    wav_tensor.float(),
                    self.model.sr,
                )
                part_paths.append(part_path)
                part_durations.append(generated_duration)
                del wav_tensor
                gc.collect()
                if torch.cuda.is_available():
                    torch.cuda.empty_cache()

            if len(part_paths) == 1:
                # Do NOT aggressively silenceremove the generated speech here:
                # low-level final phonemes can be clipped. We only normalize
                # sample rate/channel and leave the waveform intact.
                run_cmd(
                    [
                        "ffmpeg",
                        "-y",
                        "-i",
                        str(part_paths[0]),
                        "-vn",
                        "-ac",
                        "1",
                        "-ar",
                        str(DEFAULT_SAMPLE_RATE),
                        "-c:a",
                        "pcm_s16le",
                        "-loglevel",
                        "error",
                        str(output_path),
                    ]
                )
            else:
                # For long text, concatenate TTS parts without inserting an
                # artificial pause. Splitting is purely to keep each model call
                # stable; the final cue still gets fitted to one subtitle window.
                concat_list = temp_dir_path / "parts.txt"
                with concat_list.open("w", encoding="utf-8") as f:
                    for part_path in part_paths:
                        safe = str(part_path).replace("'", "'\\''")
                        f.write(f"file '{safe}'\n")

                run_cmd(
                    [
                        "ffmpeg",
                        "-y",
                        "-f",
                        "concat",
                        "-safe",
                        "0",
                        "-i",
                        str(concat_list),
                        "-ac",
                        "1",
                        "-ar",
                        str(DEFAULT_SAMPLE_RATE),
                        "-c:a",
                        "pcm_s16le",
                        "-loglevel",
                        "error",
                        str(output_path),
                    ]
                )

        # Prefer the exact duration obtained from the TTS tensors. It avoids the
        # old ffprobe=N/A failure for freshly-created WAV files.
        final_duration = sum(part_durations)

        cache_dir = output_path.parent / ".tts_cache"
        cache_dir.mkdir(parents=True, exist_ok=True)
        cache_path = cache_dir / f"{cache_key}.wav"
        shutil.copy2(output_path, cache_path)
        self.cache[cache_key] = cache_path
        return output_path, final_duration


# ---------------------------------------------------------------------------
# Audio fitting / centering
# ---------------------------------------------------------------------------

def atempo_filter_for_speed(speed: float) -> str:
    """
    Build an FFmpeg atempo chain for arbitrary positive speed factors.

    FFmpeg's atempo accepts 0.5..2.0 per filter. Chaining handles larger/smaller
    factors safely.
    """
    if speed <= 0:
        raise ValueError("speed must be positive")

    factors: list[float] = []
    remaining = speed

    while remaining > 2.0:
        factors.append(2.0)
        remaining /= 2.0

    while remaining < 0.5:
        factors.append(0.5)
        remaining /= 0.5

    factors.append(remaining)
    return ",".join(f"atempo={factor:.8f}" for factor in factors)


def fit_and_center_clip(
    input_wav: Path,
    output_wav: Path,
    window_duration: float,
    source_rate: int = DEFAULT_SAMPLE_RATE,
    margin_ms: int = DEFAULT_FIT_MARGIN_MS,
    known_duration: float | None = None,
    max_speedup: float = DEFAULT_MAX_SPEEDUP,
) -> tuple[float, float, bool]:
    """
    Return (final_speech_duration, center_delay_seconds, was_speed_adjusted).

    The output is EXACTLY window_duration seconds, containing the TTS speech
    centered when it is shorter than the available window.
    """
    clip_duration = known_duration if known_duration is not None else ffprobe_duration(input_wav)
    if clip_duration <= 0.01:
        raise RuntimeError(f"Generated TTS clip is empty: {input_wav}")

    # Leave a very small guard margin so no last phoneme sits exactly on a cue
    # boundary.
    target_duration = max(
        0.05,
        window_duration - (margin_ms / 1000.0),
    )

    was_speed_adjusted = False
    fitted_wav = output_wav.with_name(output_wav.stem + "_fitted.wav")

    if clip_duration > target_duration:
        speed = clip_duration / target_duration
        if speed > max_speedup:
            print(
                f"  WARNING: TTS is {speed:.2f}x longer than the cue. "
                "Strong time-compression may sound unnatural; "
                "consider more aggressive text compression or longer subtitle windows."
            )
        tempo_filter = atempo_filter_for_speed(speed)
        run_cmd(
            [
                "ffmpeg",
                "-y",
                "-i",
                str(input_wav),
                "-af",
                tempo_filter,
                "-ac",
                "1",
                "-ar",
                str(source_rate),
                "-c:a",
                "pcm_s16le",
                "-loglevel",
                "error",
                str(fitted_wav),
            ]
        )
        clip_for_padding = fitted_wav
        clip_duration = ffprobe_duration(fitted_wav)
        was_speed_adjusted = True
    else:
        clip_for_padding = input_wav

    # Center shorter speech in the original cue window. If the clip had to be
    # sped up, it already nearly fills the window and receives a tiny centered
    # safety margin.
    delay = max(0.0, (window_duration - clip_duration) / 2.0)

    # The final cue file is exactly the subtitle duration.
    delay_ms = int(round(delay * 1000))

    run_cmd(
        [
            "ffmpeg",
            "-y",
            "-i",
            str(clip_for_padding),
            "-af",
            f"adelay={delay_ms}:all=1,apad,atrim=0:{window_duration:.6f},"
            f"asetpts=N/SR/TB",
            "-ac",
            "1",
            "-ar",
            str(source_rate),
            "-t",
            f"{window_duration:.6f}",
            "-c:a",
            "pcm_s16le",
            "-loglevel",
            "error",
            str(output_wav),
        ]
    )

    if fitted_wav.exists():
        fitted_wav.unlink()

    return clip_duration, delay, was_speed_adjusted


# ---------------------------------------------------------------------------
# Speaker timeline creation
# ---------------------------------------------------------------------------

def make_speaker_track(
    speaker: str,
    cues: list[Cue],
    cue_files: dict[int, Path],
    total_duration: float,
    speaker_output_dir: Path,
) -> Path:
    """
    Create one full-duration speaker track from fixed-duration cue files.

    Cue files already have exact subtitle-window durations. We concatenate them
    with correctly sized silence gaps so the result is aligned to the source.
    """
    speaker_output_dir.mkdir(parents=True, exist_ok=True)

    speaker_path = speaker_output_dir / f"{safe_filename(speaker)}_dub.wav"

    ordered = sorted(cues, key=lambda c: (c.start, c.end, c.index))

    with tempfile.TemporaryDirectory(prefix="speaker_timeline_") as temp_dir:
        temp = Path(temp_dir)
        silence_cache: dict[int, Path] = {}
        sequence: list[Path] = []
        cursor = 0.0

        for cue in ordered:
            if cue.start < cursor - 0.005:
                print(
                    f"  WARNING: overlapping cues for {speaker}: "
                    f"{cue.start:.3f} < {cursor:.3f}."
                )

            gap = max(0.0, cue.start - cursor)
            if gap > 0.005:
                gap_ms = int(round(gap * 1000))
                if gap_ms not in silence_cache:
                    silence_path = temp / f"silence_{gap_ms}.wav"
                    run_cmd(
                        [
                            "ffmpeg",
                            "-y",
                            "-f",
                            "lavfi",
                            "-i",
                            f"anullsrc=channel_layout=mono:sample_rate={DEFAULT_SAMPLE_RATE}",
                            "-t",
                            f"{gap:.6f}",
                            "-c:a",
                            "pcm_s16le",
                            "-loglevel",
                            "error",
                            str(silence_path),
                        ]
                    )
                    silence_cache[gap_ms] = silence_path

                sequence.append(silence_cache[gap_ms])

            sequence.append(cue_files[cue.index])
            cursor = max(cursor, cue.end)

        tail = max(0.0, total_duration - cursor)
        if tail > 0.005:
            tail_ms = int(round(tail * 1000))
            if tail_ms not in silence_cache:
                silence_path = temp / f"silence_tail_{tail_ms}.wav"
                run_cmd(
                    [
                        "ffmpeg",
                        "-y",
                        "-f",
                        "lavfi",
                        "-i",
                        f"anullsrc=channel_layout=mono:sample_rate={DEFAULT_SAMPLE_RATE}",
                        "-t",
                        f"{tail:.6f}",
                        "-c:a",
                        "pcm_s16le",
                        "-loglevel",
                        "error",
                        str(silence_path),
                    ]
                )
                silence_cache[tail_ms] = silence_path
            sequence.append(silence_cache[tail_ms])

        if not sequence:
            raise RuntimeError(f"No timeline segments for {speaker}")

        concat_list = temp / "concat.txt"
        with concat_list.open("w", encoding="utf-8") as f:
            for item in sequence:
                safe = str(item).replace("'", "'\\''")
                f.write(f"file '{safe}'\n")

        run_cmd(
            [
                "ffmpeg",
                "-y",
                "-f",
                "concat",
                "-safe",
                "0",
                "-i",
                str(concat_list),
                "-ac",
                "1",
                "-ar",
                str(DEFAULT_SAMPLE_RATE),
                "-c:a",
                "pcm_s16le",
                "-t",
                f"{total_duration:.6f}",
                "-loglevel",
                "error",
                str(speaker_path),
            ]
        )

    return speaker_path


def mix_speaker_tracks(
    speaker_tracks: list[Path],
    output_path: Path,
    total_duration: float,
) -> None:
    """Mix <= a few speaker tracks into one mono full-duration WAV."""
    if not speaker_tracks:
        raise RuntimeError("No speaker tracks to mix.")

    if len(speaker_tracks) == 1:
        run_cmd(
            [
                "ffmpeg",
                "-y",
                "-i",
                str(speaker_tracks[0]),
                "-ac",
                "1",
                "-ar",
                str(DEFAULT_SAMPLE_RATE),
                "-t",
                f"{total_duration:.6f}",
                "-c:a",
                "pcm_s16le",
                "-loglevel",
                "error",
                str(output_path),
            ]
        )
        return

    inputs: list[str] = []
    labels: list[str] = []
    for i, track in enumerate(speaker_tracks):
        inputs.extend(["-i", str(track)])
        labels.append(f"[{i}:a]")

    filter_complex = (
        ";".join(
            f"[{i}:a]aresample={DEFAULT_SAMPLE_RATE},aformat=channel_layouts=mono[{i}a]"
            for i in range(len(speaker_tracks))
        )
        + ";"
        + "".join(f"[{i}a]" for i in range(len(speaker_tracks)))
        + f"amix=inputs={len(speaker_tracks)}:duration=longest:normalize=0[mix]"
    )

    run_cmd(
        [
            "ffmpeg",
            "-y",
            *inputs,
            "-filter_complex",
            filter_complex,
            "-map",
            "[mix]",
            "-ac",
            "1",
            "-ar",
            str(DEFAULT_SAMPLE_RATE),
            "-t",
            f"{total_duration:.6f}",
            "-c:a",
            "pcm_s16le",
            "-loglevel",
            "error",
            str(output_path),
        ]
    )


# ---------------------------------------------------------------------------
# Optional original-audio preview / video mux
# ---------------------------------------------------------------------------

def make_preview_mix(
    original_audio: Path,
    dub_audio: Path,
    output_path: Path,
    original_volume: float,
    dub_volume: float = 1.0,
) -> None:
    """
    Mix the original audio quietly under the Russian dub.

    The original track is intentionally kept audible so that music, ambience,
    room tone and sound effects remain present. This does NOT remove the
    original dialogue; the original voice will remain faintly audible.

    The dub is placed at full/near-full level by default, while the original
    can be reduced with --original-volume.
    """
    if original_volume < 0 or dub_volume < 0:
        raise ValueError("Audio volumes must be >= 0")

    # Force the original to stereo. The generated Russian dialogue is mono;
    # duplicating it to stereo makes the overlay sound natural while retaining
    # the original stereo image when the source is stereo.
    filter_complex = (
        f"[0:a]aresample={DEFAULT_SAMPLE_RATE},"
        f"aformat=sample_fmts=fltp:channel_layouts=stereo,"
        f"volume={original_volume:.6f}[orig];"
        f"[1:a]aresample={DEFAULT_SAMPLE_RATE},"
        f"aformat=sample_fmts=fltp:channel_layouts=mono,"
        f"volume={dub_volume:.6f},"
        f"pan=stereo|c0=c0|c1=c0[dub];"
        "[orig][dub]amix=inputs=2:duration=first:dropout_transition=0:"
        "normalize=0,alimiter=limit=0.97:attack=5:release=50[mix]"
    )

    run_cmd(
        [
            "ffmpeg",
            "-y",
            "-i",
            str(original_audio),
            "-i",
            str(dub_audio),
            "-filter_complex",
            filter_complex,
            "-map",
            "[mix]",
            "-ar",
            str(DEFAULT_SAMPLE_RATE),
            "-ac",
            "2",
            "-c:a",
            "pcm_s16le",
            "-loglevel",
            "error",
            str(output_path),
        ]
    )


def mux_audio_into_video(
    video_path: Path,
    dub_audio: Path,
    output_video: Path,
) -> None:
    run_cmd(
        [
            "ffmpeg",
            "-y",
            "-i",
            str(video_path),
            "-i",
            str(dub_audio),
            "-map",
            "0:v:0",
            "-map",
            "1:a:0",
            "-c:v",
            "copy",
            "-c:a",
            "aac",
            "-b:a",
            "192k",
            "-shortest",
            "-loglevel",
            "error",
            str(output_video),
        ]
    )


# ---------------------------------------------------------------------------
# Pipeline
# ---------------------------------------------------------------------------

def process(
    srt_path: Path,
    audio_path: Path,
    speaker_dir: Path,
    output_dir: Path,
    device: str,
    reference_seconds: float,
    exaggeration: float,
    cfg_weight: float,
    temperature: float,
    min_p: float,
    top_p: float,
    repetition_penalty: float,
    max_chars: int,
    interpart_pause: float,
    fit_margin_ms: int,
    seed: int,
    video_path: Path | None,
    make_preview: bool,
    original_volume: float,
    dub_volume: float,
    use_mix_for_video: bool,
    keep_clips: bool,
    t3_model: str,
    tts_retries: int,
    min_duration_ratio: float,
    max_speedup: float,
) -> None:
    ensure_ffmpeg()

    srt_path = srt_path.expanduser().resolve()
    audio_path = audio_path.expanduser().resolve()
    speaker_dir = speaker_dir.expanduser().resolve()
    output_dir = output_dir.expanduser().resolve()

    if not srt_path.exists():
        raise FileNotFoundError(f"SRT not found: {srt_path}")
    if not audio_path.exists():
        raise FileNotFoundError(f"Original audio not found: {audio_path}")
    if not speaker_dir.exists():
        raise FileNotFoundError(f"Speaker directory not found: {speaker_dir}")

    output_dir.mkdir(parents=True, exist_ok=True)
    clips_dir = output_dir / "tts_clips"
    cue_dir = output_dir / ".cue_tracks"
    refs_dir = output_dir / "voice_references"
    clips_dir.mkdir(exist_ok=True)
    cue_dir.mkdir(exist_ok=True)
    refs_dir.mkdir(exist_ok=True)

    errors_log = output_dir / "errors.log"
    if not errors_log.exists():
        errors_log.write_text("", encoding="utf-8")

    cues = parse_srt(srt_path)
    if not cues:
        raise RuntimeError("No valid [Speaker]: subtitle cues were found in the SRT.")

    total_duration = ffprobe_duration(audio_path)

    # Clamp cues to the original source duration.
    valid_cues: list[Cue] = []
    for cue in cues:
        if cue.start >= total_duration:
            continue
        end = min(cue.end, total_duration)
        if end <= cue.start:
            continue
        valid_cues.append(
            Cue(
                index=cue.index,
                start=cue.start,
                end=end,
                speaker=cue.speaker,
                text=cue.text,
            )
        )

    cues = valid_cues

    speakers = sorted({cue.speaker for cue in cues})
    print("=" * 72)
    print("CHATTERBOX RUSSIAN DUBBER")
    print("=" * 72)
    print(f"SRT:          {srt_path}")
    print(f"Audio:        {audio_path}")
    print(f"Speaker refs: {speaker_dir}")
    print(f"Output:       {output_dir}")
    print(f"Duration:     {total_duration:.2f}s")
    print(f"Cues:         {len(cues)}")
    print(f"Speakers:     {', '.join(speakers)}")
    print(f"Device:       {device}")
    print(f"Language:     {LANGUAGE_ID}")
    print(f"CFG weight:   {cfg_weight}")
    print(f"T3 model:     {t3_model}")
    print(f"TTS retries:  {tts_retries}")
    print(f"Min duration: {min_duration_ratio:.2f}x estimate")
    print("=" * 72)

    set_global_seed(seed)

    tts = ChatterboxSpeaker(
        device=device,
        exaggeration=exaggeration,
        cfg_weight=cfg_weight,
        temperature=temperature,
        min_p=min_p,
        top_p=top_p,
        repetition_penalty=repetition_penalty,
        seed=seed,
        t3_model=t3_model,
        tts_retries=tts_retries,
        min_duration_ratio=min_duration_ratio,
    )

    cues_by_speaker: dict[str, list[Cue]] = {}
    for cue in cues:
        cues_by_speaker.setdefault(cue.speaker, []).append(cue)

    cue_files_by_speaker: dict[str, dict[int, Path]] = {}
    speaker_tracks: list[Path] = []

    try:
        for speaker in speakers:
            print(f"\n{'=' * 72}\nSPEAKER: {speaker}\n{'=' * 72}")

            reference = find_speaker_reference(
                speaker=speaker,
                speaker_dir=speaker_dir,
                reference_dir=refs_dir,
                reference_seconds=reference_seconds,
                threshold_db=DEFAULT_REFERENCE_MIN_DB,
            )
            print(f"Reference: {reference}")

            # Prepare once for the whole speaker. Chatterbox's conditioning is
            # reused across all sentences until another speaker reference is set.
            tts.prepare_reference(reference)

            cue_files: dict[int, Path] = {}
            cue_files_by_speaker[speaker] = cue_files

            for pos, cue in enumerate(
                sorted(cues_by_speaker[speaker], key=lambda c: (c.start, c.index)),
                start=1,
            ):
                print(
                    f"\n[{pos}/{len(cues_by_speaker[speaker])}] "
                    f"{cue.start:.3f} -> {cue.end:.3f} "
                    f"({cue.duration:.3f}s), {word_count(cue.text)} words"
                )
                print(f"  {cue.text}")

                raw_clip = clips_dir / f"{safe_filename(speaker)}_{cue.index:06d}_raw.wav"
                fixed_clip = cue_dir / f"{safe_filename(speaker)}_{cue.index:06d}.wav"

                try:
                    known_raw_duration: float | None = None

                    if not raw_clip.exists():
                        _, known_raw_duration = tts.generate_to_file(
                            text=cue.text,
                            reference_path=reference,
                            output_path=raw_clip,
                            max_chars=max_chars,
                            interpart_pause=interpart_pause,
                        )
                    else:
                        known_raw_duration = ffprobe_duration(raw_clip)
                        if known_raw_duration <= 0.05:
                            print("  Cached TTS clip is invalid; regenerating.")
                            try:
                                raw_clip.unlink()
                            except OSError:
                                pass
                            _, known_raw_duration = tts.generate_to_file(
                                text=cue.text,
                                reference_path=reference,
                                output_path=raw_clip,
                                max_chars=max_chars,
                                interpart_pause=interpart_pause,
                            )

                    speech_duration, delay, was_speed_adjusted = fit_and_center_clip(
                        input_wav=raw_clip,
                        output_wav=fixed_clip,
                        window_duration=cue.duration,
                        source_rate=DEFAULT_SAMPLE_RATE,
                        margin_ms=fit_margin_ms,
                        known_duration=known_raw_duration,
                        max_speedup=max_speedup,
                    )

                    if was_speed_adjusted:
                        print(
                            f"  Fitted speech: {speech_duration:.3f}s "
                            f"with FFmpeg time compression; cue={cue.duration:.3f}s"
                        )
                    else:
                        print(
                            f"  Centered speech: {speech_duration:.3f}s, "
                            f"padding each side ≈ {delay:.3f}s"
                        )

                    cue_files[cue.index] = fixed_clip

                except Exception as exc:
                    error_text = (
                        f"cue={cue.index}; speaker={cue.speaker}; "
                        f"start={cue.start:.3f}; end={cue.end:.3f}; "
                        f"error={type(exc).__name__}: {exc}"
                    )
                    print(f"  ERROR: {error_text}")
                    with errors_log.open("a", encoding="utf-8") as log:
                        log.write(error_text + "\n")

                    for bad_path in (raw_clip, fixed_clip):
                        try:
                            if bad_path.exists():
                                bad_path.unlink()
                        except OSError:
                            pass

                    # Exact-duration silence keeps the timeline aligned and lets
                    # the rest of a long dubbing job continue.
                    run_cmd(
                        [
                            "ffmpeg",
                            "-y",
                            "-f",
                            "lavfi",
                            "-i",
                            f"anullsrc=channel_layout=mono:sample_rate={DEFAULT_SAMPLE_RATE}",
                            "-t",
                            f"{cue.duration:.6f}",
                            "-c:a",
                            "pcm_s16le",
                            "-loglevel",
                            "error",
                            str(fixed_clip),
                        ]
                    )
                    cue_files[cue.index] = fixed_clip

                gc.collect()
                if torch.cuda.is_available():
                    torch.cuda.empty_cache()

                if not keep_clips:
                    # Raw clips are only cache material; voice references and
                    # final speaker tracks remain.
                    try:
                        raw_clip.unlink()
                    except OSError:
                        pass

            speaker_track = make_speaker_track(
                speaker=speaker,
                cues=cues_by_speaker[speaker],
                cue_files=cue_files,
                total_duration=total_duration,
                speaker_output_dir=output_dir / "speaker_dub_tracks",
            )
            speaker_tracks.append(speaker_track)
            print(f"Speaker track: {speaker_track}")

        # Mix all Russian speakers into a single clean dialogue track.
        dub_path = output_dir / "russian_dub.wav"
        mix_speaker_tracks(
            speaker_tracks=speaker_tracks,
            output_path=dub_path,
            total_duration=total_duration,
        )
        print(f"\nRussian dub track: {dub_path}")

        mixed_path = None
        if make_preview or use_mix_for_video:
            mixed_path = output_dir / "russian_dub_mixed_with_original.wav"
            make_preview_mix(
                original_audio=audio_path,
                dub_audio=dub_path,
                output_path=mixed_path,
                original_volume=original_volume,
                dub_volume=dub_volume,
            )
            print(
                f"Mixed track: {mixed_path} "
                f"(original={original_volume:.3f}, dub={dub_volume:.3f})"
            )

        if video_path:
            video_path = video_path.expanduser().resolve()
            if not video_path.exists():
                raise FileNotFoundError(f"Video not found: {video_path}")

            out_video = output_dir / (
                f"{video_path.stem}_ru_dub_mixed.mp4"
                if use_mix_for_video
                else f"{video_path.stem}_ru_dub.mp4"
            )
            mux_audio_into_video(
                video_path=video_path,
                dub_audio=mixed_path if use_mix_for_video and mixed_path else dub_path,
                output_video=out_video,
            )
            print(f"Dubbed video: {out_video}")

        if errors_log.exists() and errors_log.stat().st_size > 0:
            print(f"WARNING: some cues were replaced with silence. See: {errors_log}")

    finally:
        # Avoid retaining the large model between separate Python operations.
        try:
            del tts.model
        except Exception:
            pass
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

        # Cue tracks are intermediate and can be deleted after the final mix.
        shutil.rmtree(cue_dir, ignore_errors=True)


# ---------------------------------------------------------------------------
# CLI helpers
# ---------------------------------------------------------------------------

def word_count(text: str) -> int:
    return len(re.findall(r"\b\w+\b", text, flags=re.UNICODE))


def default_output_dir(srt_path: Path) -> Path:
    return srt_path.parent / f"{srt_path.stem}_dub"


def build_argparser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Generate Russian speech from translated/compressed SRT using "
            "Chatterbox Multilingual voice cloning. Speaker samples come from "
            "speaker_pipeline.py's speaker_outputs directory."
        )
    )

    parser.add_argument(
        "srt",
        help="Translated/compressed SRT with [Speaker N]: text.",
    )
    parser.add_argument(
        "--audio",
        required=True,
        help="Original source audio used to determine the full timeline.",
    )
    parser.add_argument(
        "--speaker-dir",
        default=None,
        help=(
            "Directory containing Speaker_N.mp3 files from speaker_pipeline.py. "
            "Default: <srt_dir>/../speaker_outputs when possible, otherwise ./speaker_outputs"
        ),
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Output directory. Default: <srt_stem>_dub",
    )
    parser.add_argument(
        "--device",
        choices=("cuda", "cpu", "mps"),
        default=None,
        help="Chatterbox device. Default: cuda if available, then mps, then cpu.",
    )
    parser.add_argument(
        "--reference-seconds",
        type=float,
        default=DEFAULT_REFERENCE_SECONDS,
        help=f"Length of auto-created speaker reference: {DEFAULT_REFERENCE_SECONDS}s",
    )
    parser.add_argument(
        "--exaggeration",
        type=float,
        default=DEFAULT_EXAGGERATION,
        help=f"Chatterbox exaggeration (default: {DEFAULT_EXAGGERATION}).",
    )
    parser.add_argument(
        "--cfg-weight",
        type=float,
        default=DEFAULT_CFG_WEIGHT,
        help=(
            "Chatterbox CFG/Pace weight. 0 is useful for cross-language voice "
            "transfer (default: 0)."
        ),
    )
    parser.add_argument(
        "--temperature",
        type=float,
        default=DEFAULT_TEMPERATURE,
        help=f"Sampling temperature (default: {DEFAULT_TEMPERATURE}).",
    )
    parser.add_argument(
        "--min-p",
        type=float,
        default=DEFAULT_MIN_P,
        help=f"Chatterbox min_p (default: {DEFAULT_MIN_P}).",
    )
    parser.add_argument(
        "--top-p",
        type=float,
        default=DEFAULT_TOP_P,
        help=f"Chatterbox top_p (default: {DEFAULT_TOP_P}).",
    )
    parser.add_argument(
        "--repetition-penalty",
        type=float,
        default=DEFAULT_REPETITION_PENALTY,
        help=f"Repetition penalty (default: {DEFAULT_REPETITION_PENALTY}).",
    )
    parser.add_argument(
        "--max-chars",
        type=int,
        default=DEFAULT_MAX_CHARS,
        help=(
            "Maximum characters per Chatterbox generation part. Long subtitles "
            "are split internally (default: 280)."
        ),
    )
    parser.add_argument(
        "--interpart-pause",
        type=float,
        default=DEFAULT_INTERPART_PAUSE,
        help="Pause between internally split TTS parts (default: 0.12s).",
    )
    parser.add_argument(
        "--fit-margin-ms",
        type=int,
        default=DEFAULT_FIT_MARGIN_MS,
        help=(
            "Small safety margin subtracted from a cue when speeding up speech "
            f"(default: {DEFAULT_FIT_MARGIN_MS}ms)."
        ),
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=DEFAULT_SEED,
        help="Random seed. 0 = nondeterministic (default: 0).",
    )
    parser.add_argument(
        "--t3-model",
        choices=("auto", "v2", "v3"),
        default=DEFAULT_T3_MODEL,
        help=(
            "Multilingual T3 checkpoint. auto prefers V3 when the installed "
            "Chatterbox supports it, otherwise falls back to V2. "
            "Default: auto."
        ),
    )
    parser.add_argument(
        "--tts-retries",
        type=int,
        default=DEFAULT_TTS_RETRIES,
        help=(
            "Number of attempts for suspiciously short generations "
            f"(default: {DEFAULT_TTS_RETRIES})."
        ),
    )
    parser.add_argument(
        "--min-duration-ratio",
        type=float,
        default=DEFAULT_MIN_DURATION_RATIO,
        help=(
            "Reject a TTS result as too short when it is below this fraction "
            f"of a conservative text-duration estimate (default: {DEFAULT_MIN_DURATION_RATIO})."
        ),
    )
    parser.add_argument(
        "--max-speedup-warning",
        type=float,
        default=DEFAULT_MAX_SPEEDUP,
        help=(
            "Warn when fit requires more than this speech speed-up factor "
            f"(default: {DEFAULT_MAX_SPEEDUP}). This is a warning only."
        ),
    )
    parser.add_argument(
        "--video",
        default=None,
        help="Optional video file. Muxes the Russian WAV as the new audio track.",
    )
    parser.add_argument(
        "--preview-original",
        action="store_true",
        help=(
            "Also create a mixed track where the original audio is kept quietly "
            "under the Russian dub. This does NOT remove original speech."
        ),
    )
    parser.add_argument(
        "--original-volume",
        type=float,
        default=0.15,
        help=(
            "Volume of the original track when mixing it under the Russian dub. "
            "0.12 = about -18.4 dB (default: 0.12)."
        ),
    )
    parser.add_argument(
        "--dub-volume",
        type=float,
        default=1.0,
        help=(
            "Volume of the generated Russian dub in the final mix "
            "(default: 1.0)."
        ),
    )
    parser.add_argument(
        "--mix-original",
        action="store_true",
        help=(
            "Create a final mix with the original audio quietly under the "
            "Russian dub."
        ),
    )
    parser.add_argument(
        "--mix-for-video",
        action="store_true",
        help=(
            "When --video is used, mux the mixed original+Russian track instead "
            "of the clean Russian-only track."
        ),
    )
    parser.add_argument(
        "--keep-clips",
        action="store_true",
        help="Keep raw per-cue TTS WAV files for inspection.",
    )

    return parser


def choose_device(requested: str | None) -> str:
    if requested:
        if requested == "cuda" and not torch.cuda.is_available():
            raise RuntimeError("--device cuda requested, but torch.cuda.is_available() is False.")
        if requested == "mps" and not torch.backends.mps.is_available():
            raise RuntimeError("--device mps requested, but MPS is not available.")
        return requested

    if torch.cuda.is_available():
        return "cuda"
    if torch.backends.mps.is_available():
        return "mps"
    return "cpu"


def main() -> None:
    parser = build_argparser()
    args = parser.parse_args()

    srt_path = Path(args.srt).expanduser().resolve()
    audio_path = Path(args.audio).expanduser().resolve()

    if args.speaker_dir:
        speaker_dir = Path(args.speaker_dir).expanduser().resolve()
    else:
        # The typical structure is:
        # output.srt
        # speaker_outputs/Speaker_0.mp3
        # so first look next to the SRT, then in the current directory.
        candidates = [
            srt_path.parent / "speaker_outputs",
            srt_path.parent.parent / "speaker_outputs",
            Path("speaker_outputs").resolve(),
        ]
        speaker_dir = next(
            (p for p in candidates if p.exists()),
            candidates[0],
        )

    output_dir = (
        Path(args.output_dir).expanduser().resolve()
        if args.output_dir
        else default_output_dir(srt_path)
    )

    if args.reference_seconds <= 0:
        parser.error("--reference-seconds must be > 0")
    if args.max_chars < 40:
        parser.error("--max-chars should be >= 40")
    if args.interpart_pause < 0:
        parser.error("--interpart-pause must be >= 0")
    if args.fit_margin_ms < 0:
        parser.error("--fit-margin-ms must be >= 0")
    if args.tts_retries < 1 or args.tts_retries > 3:
        parser.error("--tts-retries must be between 1 and 3")
    if not 0.1 <= args.min_duration_ratio <= 1.0:
        parser.error("--min-duration-ratio must be between 0.1 and 1.0")
    if args.max_speedup_warning < 1.0:
        parser.error("--max-speedup-warning must be >= 1.0")
    if not 0.0 <= args.original_volume <= 2.0:
        parser.error("--original-volume must be between 0 and 2")
    if not 0.0 <= args.dub_volume <= 2.0:
        parser.error("--dub-volume must be between 0 and 2")
    if args.mix_for_video and not args.video:
        parser.error("--mix-for-video requires --video")

    device = choose_device(args.device)

    process(
        srt_path=srt_path,
        audio_path=audio_path,
        speaker_dir=speaker_dir,
        output_dir=output_dir,
        device=device,
        reference_seconds=args.reference_seconds,
        exaggeration=args.exaggeration,
        cfg_weight=args.cfg_weight,
        temperature=args.temperature,
        min_p=args.min_p,
        top_p=args.top_p,
        repetition_penalty=args.repetition_penalty,
        max_chars=args.max_chars,
        interpart_pause=args.interpart_pause,
        fit_margin_ms=args.fit_margin_ms,
        seed=args.seed,
        video_path=Path(args.video).expanduser().resolve() if args.video else None,
        make_preview=(args.preview_original or args.mix_original),
        original_volume=args.original_volume,
        dub_volume=args.dub_volume,
        # --mix-original is the user-facing switch for the normal workflow:
        # create the mix and, when --video is present, put that mix into the MP4.
        # --mix-for-video is retained as an explicit alias for clarity.
        use_mix_for_video=(args.mix_original or args.mix_for_video),
        keep_clips=args.keep_clips,
        t3_model=args.t3_model,
        tts_retries=args.tts_retries,
        min_duration_ratio=args.min_duration_ratio,
        max_speedup=args.max_speedup_warning,
    )


if __name__ == "__main__":
    main()
